[package]
name = "kv"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
nom = { version = "7" }
valve_kv_tools = "0.3.0"
bytemuck = { version = "1" }
dataview = { version = "1" }
log = "0.4"
env_logger = "0.11"
